# Profitable App Profiles for the App Store and Google Play Markets


#### Aim : To find new App profiles that can attract more users and have more chances of success by analysing the available dataset  from Google Playstore and iOS App store. 



This data analysis project is done for an app building company to help them find better app profiles that have good traction by analysing exisiting app data from Google play store and iOS app store. 


The goal of the company is to build Free apps and generate revenue through in-app ads.


The more people download and use the app, the more people will be interacting with the in-app ads. This in turn increases the revenue from the app. So more people, more download and more profit is the basic equation here. 


**So our goal for this project is to analyze data to help our developers understand what type of apps are likely to attract more users and increase the number of downloads.**



In order to achieve this goal we are going to find datasets that are connected with Google  and iOS app stores and analyse it. 


As of September 2018, there were approximately 2 million iOS apps available on the App Store, and 2.1 million Android apps on Google Play. It will be a huge task to collect all this data. So we will be going to analyse a small sample dataset. 


## Datasets


There are two data sets that seem suitable for our goals:

   * A [data set](https://www.kaggle.com/lava18/google-play-store-apps) containing data about approximately 10,000 Android apps from Google Play 
   * A [data set](https://www.kaggle.com/ramamet4/app-store-apple-data-set-10k-apps) containing data about approximately 7,000 iOS apps from the App Store

Google playstore data was collected in August 2018. You can download the data set directly from this [Link](https://dq-content.s3.amazonaws.com/350/googleplaystore.csv).
iOS Appstore data was collected in July 2017. You can download the data set directly from this [Link](https://dq-content.s3.amazonaws.com/350/AppleStore.csv).





# Opening The Data set


In [1]:
#Opening the files

opened_data_apple= open(r"\Users\Surface GO\Downloads\AppleStore.csv", encoding = "UTF-8")
opened_data_google= open(r"\Users\Surface GO\Downloads\googleplaystore.csv", encoding = "UTF-8")


from csv import reader          #to get csv reading capabilities from CSV library


#reading the files

read_apple_data= reader(opened_data_apple)     # we are using reader() function from csv library
read_google_data=reader(opened_data_google)


#making them into list for data manipulations

ios_app_list=list(read_apple_data)             # we are using list() function to create a list
google_app_list=list(read_google_data)


#getting the header, ie the first row

ios_header=ios_app_list[0]                  #fetches the fist row from the list
google_app_header=google_app_list[0]        #fetches the fist row from the list


#getting the app data w/o header

ios_apps=ios_app_list[1:]          # this will read all rows except the header row at '0'
google_apps=google_app_list[1:]    # this will read all rows except the header row at '0'



# Exploring the dataset

We are going to create a function to explore the data by printing the data slices and to check number of rows and columns in the whole data set. For that purpose a function named explore_data() will be defined and it can be repeatedly used to print rows in a readable way.

In [2]:

# to explore the data we need to specify which dataset to use, starting and ending row
# if you want to find the number of rows and columns, specify True or False



def explore_data(dataset, start, end, rows_and_columns=False):
    
    dataset_slice=dataset[start:end]            # slices dataset from the start and end rows provided
    for row in dataset_slice:
        print(row,'\n')                         #prints each row of the sliced dataset in a new line
        
                                                # if rows and colums in specified as True   
            
    if rows_and_columns:                                                
        print('Number of rows: ', len(dataset))          # find the length of the dataset, ie the no. of rows
        print('Number of Columns: ', len(dataset[0]))   #find the length of first row, ie no of columns

# Lets Explore the data now

Let us start by printing the first 3 rows of each data set and checking the total number of Rows and columns in each data set. We will also check the column names to get a better understanding of the data we are analysing. 

But before that let us write a function to find the index of the header items. 

## Index finding function

This is a function created to get the index of header elements in a dataset. To get the  index, call the function with the dataset name as argument.

In [3]:
def indexer(dataset_header):         # Input the dataset header to retrieve its index
    index=0
    print("Index")                   #### is there a way to print the variable name used? (eg. index of appstore)
    for column_name in dataset_header:      #finding each column name from the header row
        print(index, ' : ', column_name)    
        index+=1
    print('\n \n')
        

## Now let us print the ios Header
We use explore_data function to print first 3 rows of iOS dataset.

In [4]:
print("------------------ios Header------------------", '\n', '\n', ios_header,'\n','\n')


print("------------------ios 3 rows of data------------------\n \n")
explore_data(ios_apps,0,3, True)



------------------ios Header------------------ 
 
 ['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic'] 
 

------------------ios 3 rows of data------------------
 

['284882215', 'Facebook', '389879808', 'USD', '0.0', '2974676', '212', '3.5', '3.5', '95.0', '4+', 'Social Networking', '37', '1', '29', '1'] 

['389801252', 'Instagram', '113954816', 'USD', '0.0', '2161558', '1289', '4.5', '4.0', '10.23', '12+', 'Photo & Video', '37', '0', '29', '1'] 

['529479190', 'Clash of Clans', '116476928', 'USD', '0.0', '2130805', '579', '4.5', '4.5', '9.24.12', '9+', 'Games', '38', '5', '18', '1'] 

Number of rows:  7197
Number of Columns:  16


# iOS Header and its Description

Let us now check what are the items mentioned in the iOS header and what their descriptions are.


We have found out that below mentioned items are in iOS header

 
 'id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic'
 

0 : "id" : App ID

1: "track_name": App Name

2: "size_bytes": Size (in Bytes)

3: "currency": Currency Type

4: "price": Price amount

5: "ratingcounttot": User Rating counts (for all version)

6: "ratingcountver": User Rating counts (for current version)

7: "user_rating" : Average User Rating value (for all version)

8: "userratingver": Average User Rating value (for current version)

9: "ver" : Latest version code

10: "cont_rating": Content Rating

11: "prime_genre": Primary Genre

12: "sup_devices.num": Number of supporting devices

13: "ipadSc_urls.num": Number of screenshots showed for display

14: "lang.num": Number of supported languages

15: "vpp_lic": Vpp Device Based Licensing Enabled

You can find more details regarding the header description [here](https://www.kaggle.com/ramamet4/app-store-apple-data-set-10k-apps)
 
 
## Index of iOS Header


In [5]:
indexer(ios_header)   #we called the indexer function with ios_header as the argument

Index
0  :  id
1  :  track_name
2  :  size_bytes
3  :  currency
4  :  price
5  :  rating_count_tot
6  :  rating_count_ver
7  :  user_rating
8  :  user_rating_ver
9  :  ver
10  :  cont_rating
11  :  prime_genre
12  :  sup_devices.num
13  :  ipadSc_urls.num
14  :  lang.num
15  :  vpp_lic

 



# Now let us print the Google Playstore App Header
We use explore_data function to print first 3 rows of Google app store dataset.

In [6]:
print("\n \n ------------------Google App Header------------------", '\n', '\n', google_app_header,'\n','\n')

print("\n ------------------google apps 3 rows of data------------------ \n")
explore_data(google_apps,0,3, True)


 
 ------------------Google App Header------------------ 
 
 ['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver'] 
 


 ------------------google apps 3 rows of data------------------ 

['Photo Editor & Candy Camera & Grid & ScrapBook', 'ART_AND_DESIGN', '4.1', '159', '19M', '10,000+', 'Free', '0', 'Everyone', 'Art & Design', 'January 7, 2018', '1.0.0', '4.0.3 and up'] 

['Coloring book moana', 'ART_AND_DESIGN', '3.9', '967', '14M', '500,000+', 'Free', '0', 'Everyone', 'Art & Design;Pretend Play', 'January 15, 2018', '2.0.0', '4.0.3 and up'] 

['U Launcher Lite – FREE Live Cool Themes, Hide Apps', 'ART_AND_DESIGN', '4.7', '87510', '8.7M', '5,000,000+', 'Free', '0', 'Everyone', 'Art & Design', 'August 1, 2018', '1.2.4', '4.0.3 and up'] 

Number of rows:  10841
Number of Columns:  13



# Google App Header and its Description
 
 'App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver'
 
 
0: App : Application name

1: Category :Category the app belongs to

2: Rating : Overall user rating of the app (as when scraped)

3: Reviews: Number of user reviews for the app (as when scraped)

4: Size: Size of the app (as when scraped)

5: Installs: Number of user downloads/installs for the app (as when scraped)

6: Type:Paid or Free

7: Price : Price of the app (as when scraped)

8: Content Rating: Age group the app is targeted at - Children / Mature 21+ / Adult

9: Genres: An app can belong to multiple genres (apart from its main category). For eg, a musical family game will belong to

You can find more details here https://www.kaggle.com/lava18/google-play-store-apps

## Index of Google Playstore App Header
We use the indexer function to get the index of Google playstore app header.
 

In [7]:
indexer(google_app_header)   #callind indexer function with google_app_header as argument.

Index
0  :  App
1  :  Category
2  :  Rating
3  :  Reviews
4  :  Size
5  :  Installs
6  :  Type
7  :  Price
8  :  Content Rating
9  :  Genres
10  :  Last Updated
11  :  Current Ver
12  :  Android Ver

 



# Data Cleaning  | Stage 1

We need to check if the given dataset is free of errors. If there are any errors, we need to rectify them or remove them.Also we are looking at creating apps that are free to download and that are presented for in English language. 

So we also need to remove the data of apps

 * that are not free to download and install, 
 * that are not in English language 



## Error Finding Step

We are looking for errors in the dataset. We can first check if there are any column values missing in the dataset. To check that we can compare if the lenth of the header(the row containing column names) is same as that of each the rows in the data set. 

If the length of header is not equal to the length of any row, that means, the row is either missing a value or in some case has an additional value. In both cases, there is an error in that row and we need to rectify it. 

In [8]:
ios_header_length=len(ios_header)                   # finding the length of ios apps' header
print("Length of ios header is : ", ios_header_length)

google_app_header_length=len(google_app_header)     #finding the length of google app header
print("Length of google app header is : ", google_app_header_length)


Length of ios header is :  16
Length of google app header is :  13


In [9]:
# Checking if the length of each row in ios app data set is equal to that of the header length.
# If it is not of the same length, mostly a column value must be missing. So we will print out that row. 


for app in ios_apps:
    if len(app)!=ios_header_length:   # checking if length of each row not equal to the length of header
                                      # if the length is not equal, its an error in data and prints that row
        print(app)                                                          #printing the content of the row
        print("Index of the row with error is: ",ios_apps.index(app))       #printing the index of that row  
        print("Length of ios app row is : ",len(app))

It didn't print any row which means all the columns have data corresponding to the items mentioned in the header row. 
So there is no error in that regards. 

Now we will move onto Google Playstore app data. We Repeat the same steps for google apps' data set too and print out the row and its index. 

In [10]:
for app in google_apps:
    if len(app)!=google_app_header_length:
        print(app)
        print("Index of the row with error is: ",google_apps.index(app))
        print("Length of google app row is : ", len(app))

['Life Made WI-Fi Touchscreen Photo Frame', '1.9', '19', '3.0M', '1,000+', 'Free', '0', 'Everyone', '', 'February 11, 2018', '1.0.19', '4.0 and up']
Index of the row with error is:  10472
Length of google app row is :  12


We have found out that ios app data doesn't have any missing columns. But that of google apps have missing values. It only has 12 values instead of 13. 

Now we need to delete the row that has missing values. 

In [11]:
print(len(google_apps))
del google_apps[10472]
print(len(google_apps))

10841
10840


We have successfully deleted one row that was at the index 10472 and confirmed it by checking the lenght of google apps data before and after. So now we have a dataset that has all corresponding values. But there can be duplicate value. Now we have to find that. 

# Finding the Duplicate entry

Now we need to check if there are any duplicate entries in our dataset. One way to check it is by using its app name or app id. For iOS the unique identifier is the app id while google apps, the unique id is the app name iteself. So let us first check duplicate entries in iOS dataset.



To do that we will create two empty lists, unique list and duplicate list. 

Inside the loop, the app_id will be checked agaist all entries in the unique list one by one. Initially unique list will be empty and the first entry will be appended to that list. After this, the subsequent app_ids will be checked against the entries in the unique list. If a match is found, that app_id will be appended to duplicate list.  So finally all the duplicate entries will end up in duplicate list while the unique ones in the unique list. 

( Note: If you are using app_name for iOS apps, you will find 2 duplicate entries. But their app_id and most other values are unique except for the app name. So it could be a different version of the app and lets not consider it as duplicate entry)

In [12]:
ios_unique_list=[]                           # creating an empty list to store unique app names
ios_duplicate_list=[]                        # creating an empty list to store duplicate app names 

for row in ios_apps:                         #picking each app data in ios app dataset
    app_id=row[0]                            #assigning the value at index 0 as app_id
    
    if app_id in ios_unique_list:            #if app_id is found in unique list
        #print(ios_apps.index(row))              #print the index of that row  
        ios_duplicate_list.append(app_id)        #and add the name to duplicate list
        
    else:                                    #if app_id is NOT found in unique list
        ios_unique_list.append(app_id)           #add it to the unique list      
        


# Once the loop is exited, print the list of duplicate list
        
print(ios_duplicate_list)
print("There are ", len(ios_duplicate_list), " duplicate app entries in ios dataset")

[]
There are  0  duplicate app entries in ios dataset


There was no duplicate entry in the iOS app data. So we can move to google app data now. 

Using the same logic as above, we will go through google app dataset to find the duplicate entry. But instead of app_id we will use app_name.

In [13]:
unique_list=[]
duplicate_list=[]

for row in google_apps:
    app_name=row[0]
    
    if app_name in unique_list:
        duplicate_list.append(app_name)
    else:
        unique_list.append(app_name)        

print("Number of duplicate entries in Google apps' data set: ", len(duplicate_list))  
    

Number of duplicate entries in Google apps' data set:  1181


So after our inspection, we can see that in ios app list, there are no duplicate entries, while in google app's list there are 1181 duplicate entries. 

Now we need to remove these duplicate entries from our data set. In order to do that let us take a look at a few sample duplicate entries and find a logic to delete them. Let us first retrieve first 26 duplicate entries from our duplicate list. 

In [14]:
duplicate_list[:25]

['Quick PDF Scanner + OCR FREE',
 'Box',
 'Google My Business',
 'ZOOM Cloud Meetings',
 'join.me - Simple Meetings',
 'Box',
 'Zenefits',
 'Google Ads',
 'Google My Business',
 'Slack',
 'FreshBooks Classic',
 'Insightly CRM',
 'QuickBooks Accounting: Invoicing & Expenses',
 'HipChat - Chat Built for Teams',
 'Xero Accounting Software',
 'MailChimp - Email, Marketing Automation',
 'Crew - Free Messaging and Scheduling',
 'Asana: organize team projects',
 'Google Analytics',
 'AdWords Express',
 'Accounting App - Zoho Books',
 'Invoice & Time Tracking - Zoho',
 'join.me - Simple Meetings',
 'Invoice 2go — Professional Invoices and Estimates',
 'SignEasy | Sign and Fill PDF and other Documents']

Now that we have a some names of the duplicate entries, we can pick a few app names in random and see their duplicate entries. 

In [15]:
# We randomly picked the app 'Slack' to check its duplicate entries

for app in google_apps:
    if app[0]=='Slack':
        print(app)

['Slack', 'BUSINESS', '4.4', '51507', 'Varies with device', '5,000,000+', 'Free', '0', 'Everyone', 'Business', 'August 2, 2018', 'Varies with device', 'Varies with device']
['Slack', 'BUSINESS', '4.4', '51507', 'Varies with device', '5,000,000+', 'Free', '0', 'Everyone', 'Business', 'August 2, 2018', 'Varies with device', 'Varies with device']
['Slack', 'BUSINESS', '4.4', '51510', 'Varies with device', '5,000,000+', 'Free', '0', 'Everyone', 'Business', 'August 2, 2018', 'Varies with device', 'Varies with device']


In [16]:
# We randomly picked the app 'Facebook' to check its duplicate entries


for app in google_apps:
    if app[0]=='Facebook':
        print(app)

['Facebook', 'SOCIAL', '4.1', '78158306', 'Varies with device', '1,000,000,000+', 'Free', '0', 'Teen', 'Social', 'August 3, 2018', 'Varies with device', 'Varies with device']
['Facebook', 'SOCIAL', '4.1', '78128208', 'Varies with device', '1,000,000,000+', 'Free', '0', 'Teen', 'Social', 'August 3, 2018', 'Varies with device', 'Varies with device']


In [17]:
# We randomly picked the app 'Google My Business' to check its duplicate entries


for app in google_apps:
    if app[0]=='Google My Business':
        print(app)

['Google My Business', 'BUSINESS', '4.4', '70991', 'Varies with device', '5,000,000+', 'Free', '0', 'Everyone', 'Business', 'July 24, 2018', '2.19.0.204537701', '4.4 and up']
['Google My Business', 'BUSINESS', '4.4', '70991', 'Varies with device', '5,000,000+', 'Free', '0', 'Everyone', 'Business', 'July 24, 2018', '2.19.0.204537701', '4.4 and up']
['Google My Business', 'BUSINESS', '4.4', '70991', 'Varies with device', '5,000,000+', 'Free', '0', 'Everyone', 'Business', 'July 24, 2018', '2.19.0.204537701', '4.4 and up']


After analysing a few apps randomly, we have found out that the only change that occurs is the 4th column (at index 3) which is **the total number of reviews** at the time of scraping this data. 

The number of rating is increasing means, the data might have been collected at different times. So it is a better logic to keep the latest information, ie the data with higher number of rating. **So let us keep the row with more number of ratings among the duplicate entries and delete the rest.**

In order to do that, we will create a dictionary to update the app's data with the latest values and delete the rest of the duplicate entries. We will use this dictionary in turn to create a new list without the duplicate entries. 

We are going to add the row of data to this empty dictionary if the value of rating is the highest among the duplicate entries. 


On the first iteration, it initially checks if there is any app name in the empty dictionary. Since there are no app_names in the empty dictionary, it goes to execute the next condition that adds a key:value pair to the dictionary with app_name: app_rating. 

On the next iteration, if a same app_name is found, and if the value corresponding to that key is less than app_rating given in the dataset in that iteration, value of the key gets updated with new higher app rating. And this process continues till all the apps listed in the dataset is checked. 



In [18]:
google_app_dictionary={}                  # defining an empty dictionary to store the data

for app in google_apps:
    app_name=app[0]
    app_rating=float(app[3])
    
    # if app_name is in google_app_dictionary 
    # and if the value of dictionary (which is the app_rating) with a key=app_name  is less than app rating
    # then update value of dictionary key with new app rating. 
    
    if app_name in google_app_dictionary and google_app_dictionary[app_name]<app_rating:
        google_app_dictionary[app_name]=app_rating            # Updating the dictionary with higher values
        
        
    #if app_name is not found in google_app_dictionary 
    # add it to dictionary with corresponding app_rating
        
    elif app_name not in google_app_dictionary:
        google_app_dictionary[app_name]=app_rating           # Adding the dictionary with new key:value pair
        
        
        
# Else statement is not used since it can add app_name:app_ratings whenever the first statement becomes false
# and it can contain app_name with lower app_ratings and will still have duplicate entry.
        

    

So let us cross check if we have removed all 1181 duplicate entries by a simple calculation, ie by comparing the length of dictionary we created without duplicate entries with the expected length we received from our calculation.

In [19]:
print("Actual length:", len(google_app_dictionary))  # finding the length of new dictionary we created w/o duplication

print( "Expected length:", len(google_apps)-1181)    # subtracting number of duplicate entries from total entries

Actual length: 9659
Expected length: 9659


Since both values are same, we have successully eliminated the duplicate entries and updated the app names with the highest rating using our dictionary.


Now we are going to create list from this dictionary for more flexible analysis. We do this by comparing the value of app_rating in both the newly created dictionary and in the google app dataset. If the value of app_rating matches, that row from google_app_dataset will be added to the clean_list. 

Another list will keep track of all app_names that has been added so far. By checking if the app_name is present here, we can avoid entering duplicate row of data. 

In [20]:
clean_google_apps=[]                   # defining an empty list to store clean app data
already_added_apps=[]                  # defining an empty list to help prevent duplication of entries


for row in google_apps:                # iterates through google_app dataset
    app_name=row[0]
    app_rating=float(row[3])
    
    
    # if the dictionary value paired with key=app_name is same
    # and the app_name is not already added
    # then clean_google_apps list gets appended
    # and the already_added_apps list gets updated with the latest app_name
    
    if google_app_dictionary[app_name]==app_rating and app_name not in already_added_apps:
        clean_google_apps.append(row)
        already_added_apps.append(app_name)
        
            
            
print("Actual length of clean data", len(clean_google_apps))
print( "Expected length:", len(google_apps)-1181)

Actual length of clean data 9659
Expected length: 9659


# Data Cleaning | Stage : 2

From our initial dataset, we have removed rows that have data missing and removed the duplicate entries. Now we have a clean dataset. But our requirement is a dataset with Free and Non-English app data. So we need to remove all the data related to apps that are not free and not in English. So that will be our data cleaning stage 2. 


## Finding the Non-English Apps 

To find non-English apps, we need to make use of the ASCII (American Standard Code for Information Interchange) system. 

The numbers corresponding to the characters we commonly use in an English text are all in the range 0 to 127, according to the ASCII  system. Based on this number range, we can build a function that detects whether a character belongs to the set of common English characters or not. If the number is equal to or less than 127, then the character belongs to the set of common English characters.

If an app name contains a character that is greater than 127, then it probably means that the app has a non-English name or it has some non-English character.

Any emoji or special character will also be considered as non-English character as it's value is higher than 127. There can be some app names that contains an emoji or two. So if we judge an app to be non-English just because of one emoji or special character, that will be a wrong move. So we will decide that if there are more than 3 non-English character, we will reject that app as non-English app. Though this might not be a fool-proof logic, but it works fine for our analysis here without creating a big difference. 

In [21]:
def english_checker(app_name):              # defining the function to find non-English character
    non_english_char=0    
    
    for character in app_name:              # iterates through each character of the app_name
        if ord(character) > 127:            # ord() function helps to find the ASCII value of each character
            non_english_char += 1           # Counts the number of non-English character
                    
        
    if non_english_char > 3:                # checks if non-English characters are more than 3
        return False                        # if it is more than 3, returns with False, meaning Non-English app
    else:        
        return True                         # if it is less than 3, returns with True, meaning English app
        


Using this english_checker function, we are going to create a list that contains apps that are in English only. This will be a list containing already cleaned data but without non-English app entries. 

In [22]:
clean_english_google_apps=[]             # an empty list to store clean, English google apps
clean_english_ios_apps=[]                # an empty list to store clean, English iOS apps



# Creating clean_English_Google_Apps


for app in clean_google_apps:   
    app_name=app[0]
    if english_checker(app_name):       # if english_checker function returns True, append the list with app row
        clean_english_google_apps.append(app)
        
print("No. of English Google Apps: ", len(clean_english_google_apps))



# Creating clean_English_iOS_Apps


for app in ios_apps:
    app_name=app[1]
    if english_checker(app_name):     # if english_checker function returns True, append the list with app row
        clean_english_ios_apps.append(app)
        
print("No. of English ios Apps: ", len(clean_english_ios_apps))
   

No. of English Google Apps:  9614
No. of English ios Apps:  6183


# Finding Free Apps

Now that we have clean dataset with apps in English, we need to find the apps that are Free to download. All we need to check is if the price of the app is given as 0 or not. 

Note: The price is given as '0' in the case of google apps while '0.0' in the case of iOS apps. Both are string type. So when comparing, compare the strings. 


In [23]:
free_english_google_apps=[]             # an empty list to store Free English Google apps
free_english_ios_apps=[]                # an empty list to store Free English iOS apps



# Creating clean_Free_English_Google_Apps


for app in clean_english_google_apps:
    price=app[7]    
    if price=='0':
        free_english_google_apps.append(app)
        
print("No. of Free, English Google apps: ", len(free_english_google_apps))



# Creating clean_Free_English_iOS_Apps


for app in clean_english_ios_apps:
    price=app[4]
    if price=='0.0':
        free_english_ios_apps.append(app)
        
print("No. of Free, English iOS apps: ", len(free_english_ios_apps))

No. of Free, English Google apps:  8864
No. of Free, English iOS apps:  3222


We have successfully finished the data cleaning part. Now we have 2 data sets that are in accordance with our requirement. There are no missing values and no duplicate entries. Also all no Non-English and non-Free apps have been removed. Now we have clean data sets to work with. So it is time to do some analysis. 


# Analysing the Data sets



Our aim is to determine the kinds of apps that are likely to attract more users because our revenue is highly influenced by the number of people using our apps.

To minimize risks and overhead, our validation strategy for an app idea is comprised of three steps:

 * Build a minimal Android version of the app, and add it to Google Play.
 * If the app has a good response from users, we develop it further.
 * If the app is profitable after six months, we build an iOS version of the app and add it to the App Store.
 
Because our end goal is to add the app on both Google Play and the App Store, we need to find app profiles that are successful on both markets. 

Let's begin the analysis by getting a sense of what are the most common genres for each market. For this, we'll need to build frequency tables for a few columns in our data sets.


In [24]:
def freq_table(dataset,index):              # defining a function to create Frequency table of any index in the dataset
    table={}
    total=0
    
    for row in dataset:                     # iterates through the dataset
        total+=1                            # To count total number of rows in a dataset
        key=row[index]                      # assigns dictionary key as row data at that index
        if key in table:                    # if that key is found in the table
            table[key]+=1                   # the value of key gets updated by 1
        else:
            table[key]=1                    # else a new key is created with value 1
            
            
    table_percentage={}                     # creates an empty table to store the percentage value
        
    for key in table:                       #iterates through the frequency table just created
        percentage=(table[key]/total)*100   # calculate the percentage of each value
        table_percentage[key]=percentage    # adds the key:value pair to the percentage table
            
    return table_percentage                 # the fuction retuns table percentage dictionary


In [25]:
def display_table(dataset,index):           # defines a function to return a sorted percentage of frequency table
    table = freq_table(dataset, index)      # creates a frequency table dictionary for the given dataset
    table_display = []                      # creates an empty list to store the key, value pair as tuple
    
    
    for key in table:                                 # iterates through the frequency table
        key_val_as_tuple = (table[key], key)          # stores as value, key tuple; value stored first in order to sort
        table_display.append(key_val_as_tuple)        # append the list with key value tuple
        
    
    # Sorts the list and prints in descending order

    table_sorted = sorted(table_display, reverse = True)         #sorts the frequency table in descending order
    for entry in table_sorted:                                   # iterates through the sorted table
        print(entry[1], ':', entry[0])                           # and prints in the Key: Value format

### Google apps based on category

Now let us use this display_table function to list down the top google apps based on its categories.

In [26]:
print("Google Apps based on Categories \n")
display_table(free_english_google_apps,1)     # category is at the index 1

Google Apps based on Categories 

FAMILY : 18.907942238267147
GAME : 9.724729241877256
TOOLS : 8.461191335740072
BUSINESS : 4.591606498194946
LIFESTYLE : 3.9034296028880866
PRODUCTIVITY : 3.892148014440433
FINANCE : 3.7003610108303246
MEDICAL : 3.531137184115524
SPORTS : 3.395758122743682
PERSONALIZATION : 3.3167870036101084
COMMUNICATION : 3.2378158844765346
HEALTH_AND_FITNESS : 3.0798736462093865
PHOTOGRAPHY : 2.944494584837545
NEWS_AND_MAGAZINES : 2.7978339350180503
SOCIAL : 2.6624548736462095
TRAVEL_AND_LOCAL : 2.33528880866426
SHOPPING : 2.2450361010830324
BOOKS_AND_REFERENCE : 2.1435018050541514
DATING : 1.861462093862816
VIDEO_PLAYERS : 1.7937725631768955
MAPS_AND_NAVIGATION : 1.3989169675090252
FOOD_AND_DRINK : 1.2409747292418771
EDUCATION : 1.1620036101083033
ENTERTAINMENT : 0.9589350180505415
LIBRARIES_AND_DEMO : 0.9363718411552346
AUTO_AND_VEHICLES : 0.9250902527075812
HOUSE_AND_HOME : 0.8235559566787004
WEATHER : 0.8009927797833934
EVENTS : 0.7107400722021661
PARENTING : 0.

From this sorted percentage table for google apps we have seen that Family category is leading with close to 19% among the free English apps falling under this category, almost double compared to the second in line, the Game apps with 9.7%. 
Before we continue to next category, lets have a quick look into the Family apps to see what kind of apps do they actually have. 



In [70]:
count=0
for app in free_english_google_apps:
    if app[1]=='FAMILY':                # to print only those apps with the name 'Family'
        count+=1
        print(app[0], ':', app[8])      # prints App_name:content rating; to check the focussed audience
        if count==25:                   # to print only 25 items
            break

Jewels Crush- Match 3 Puzzle : Everyone
Coloring & Learn : Everyone
Mahjong : Everyone
Super ABC! Learning games for kids! Preschool apps : Everyone
Toy Pop Cubes : Everyone
Educational Games 4 Kids : Everyone
Candy Pop Story : Everyone
Princess Coloring Book : Everyone
Hello Kitty Nail Salon : Everyone
Candy Smash : Everyone
Happy Fruits Bomb - Cube Blast : Everyone
Princess Adventures Puzzles : Everyone
Kids Educational Game 3 Free : Everyone
Puzzle Kids - Animals Shapes and Jigsaw Puzzles : Everyone
Coloring book moana : Everyone
Baby Panda Care : Everyone
Kids Educational :All in One : Everyone
Number Counting games for toddler preschool kids : Everyone
Learn To Draw Glow Flower : Everyone
No. Color - Color by Number, Number Coloring : Everyone
Draw.ly - Color by Number Pixel Art Coloring : Everyone
Baby puzzles : Everyone
Garden Fruit Legend : Everyone
Barbie™ Fashion Closet : Everyone
Candy Day : Everyone


After going through a random samples of apps under Family category,we can safely say that Family apps are mainly games and activity apps for kids and teens. Most of them can very well be grouped under games category too. That makes the major percentage of google apps falling under games category. 

Since games and Family category is quite saturated, it won't be a wise decision to enter into that category with yet another new app.

But before getting into any more analysis, let us look google apps based on Genre, as there is one more segregation provided by genres

### Google apps based on Genre

In [28]:
print("Google Apps based on Genre \n")
display_table(free_english_google_apps,9)

Google Apps based on Genre 

Tools : 8.449909747292418
Entertainment : 6.069494584837545
Education : 5.347472924187725
Business : 4.591606498194946
Productivity : 3.892148014440433
Lifestyle : 3.892148014440433
Finance : 3.7003610108303246
Medical : 3.531137184115524
Sports : 3.463447653429603
Personalization : 3.3167870036101084
Communication : 3.2378158844765346
Action : 3.1024368231046933
Health & Fitness : 3.0798736462093865
Photography : 2.944494584837545
News & Magazines : 2.7978339350180503
Social : 2.6624548736462095
Travel & Local : 2.3240072202166067
Shopping : 2.2450361010830324
Books & Reference : 2.1435018050541514
Simulation : 2.0419675090252705
Dating : 1.861462093862816
Arcade : 1.8501805054151623
Video Players & Editors : 1.7712093862815883
Casual : 1.7599277978339352
Maps & Navigation : 1.3989169675090252
Food & Drink : 1.2409747292418771
Puzzle : 1.128158844765343
Racing : 0.9927797833935018
Role Playing : 0.9363718411552346
Libraries & Demo : 0.9363718411552346
Auto

This segregation of apps is a bit more specific and in depth. For our analysis of finding a more profitable app, we really don't need this much of detailing. So we can use the broader classification as given by the categories. So further analysis we will make use of app classification based on categories. 

### iOS apps based on categories

In [29]:
display_table(free_english_ios_apps, 11)

Games : 58.16263190564867
Entertainment : 7.883302296710118
Photo & Video : 4.9658597144630665
Education : 3.662321539416512
Social Networking : 3.2898820608317814
Shopping : 2.60707635009311
Utilities : 2.5139664804469275
Sports : 2.1415270018621975
Music : 2.0484171322160147
Health & Fitness : 2.0173805090006205
Productivity : 1.7380509000620732
Lifestyle : 1.5828677839851024
News : 1.3345747982619491
Travel : 1.2414649286157666
Finance : 1.1173184357541899
Weather : 0.8690254500310366
Food & Drink : 0.8069522036002483
Reference : 0.5586592178770949
Business : 0.5276225946617008
Book : 0.4345127250155183
Navigation : 0.186219739292365
Medical : 0.186219739292365
Catalogs : 0.12414649286157665


In iOS apps also the games category is leading but here more than half of the free english apps falls under this category. Second one is entertainment with just under 8% share. By scanning through the categories and from the number of apps in those segments we can say that Appstore is dominated by for-fun apps while google play store has a balance of fun and functionality as it has similar quantities of practical use apps as well. 

We have an understanding of number of apps made in each categories/genres. 


# Finding the Apps that has more users from the top genres

Now we know that which of these categories/genres have most number of apps made. But we don't know out of these genres, which genre has more users. In order to find that we can look into the average users in each genres. To find that we can use the number of instals if it is available. But for iOS app data, number of installs isn't avaliable. So as an alternative option, we can look into using total number of user rating. 

Now let us find the popularity of iOS apps in each categories. For that we can use rating_count_tot at index 5

# iOS App Most Popular

In [56]:
ios_genre=freq_table(free_english_ios_apps,11)  # To list down all the genres present in iOS app store
print(ios_genre)

{'Social Networking': 3.2898820608317814, 'Photo & Video': 4.9658597144630665, 'Games': 58.16263190564867, 'Music': 2.0484171322160147, 'Reference': 0.5586592178770949, 'Health & Fitness': 2.0173805090006205, 'Weather': 0.8690254500310366, 'Utilities': 2.5139664804469275, 'Travel': 1.2414649286157666, 'Shopping': 2.60707635009311, 'News': 1.3345747982619491, 'Navigation': 0.186219739292365, 'Lifestyle': 1.5828677839851024, 'Entertainment': 7.883302296710118, 'Food & Drink': 0.8069522036002483, 'Sports': 2.1415270018621975, 'Book': 0.4345127250155183, 'Finance': 1.1173184357541899, 'Education': 3.662321539416512, 'Productivity': 1.7380509000620732, 'Business': 0.5276225946617008, 'Catalogs': 0.12414649286157665, 'Medical': 0.186219739292365}


In [58]:
a_list=[]                 # an empty list to add genre and average rating
for genre in ios_genre:  # we need to pick one genre each and check for them in the whole data and add their ratings
    
    app_rating=0
    total=0
    for app in free_english_ios_apps:
        if genre==app[11]:              # if the genre in ios_genre dictionary is same as the genre in dataset
            total+=1                    # count the total
            app_rating+=float(app[5])   # adding the app_ratings
    average_rating=app_rating/total     # finding the average app_rating
    b_list=(average_rating, genre)      # a dummy list to store average rating and genre as tuple
    a_list.append(b_list)               # append (average_rating, genre) tuple to a list
    
print (sorted(a_list, reverse=True))    # print the sorted (average_rating,genre) list
    
    

[(86090.33333333333, 'Navigation'), (74942.11111111111, 'Reference'), (71548.34905660378, 'Social Networking'), (57326.530303030304, 'Music'), (52279.892857142855, 'Weather'), (39758.5, 'Book'), (33333.92307692308, 'Food & Drink'), (31467.944444444445, 'Finance'), (28441.54375, 'Photo & Video'), (28243.8, 'Travel'), (26919.690476190477, 'Shopping'), (23298.015384615384, 'Health & Fitness'), (23008.898550724636, 'Sports'), (22788.6696905016, 'Games'), (21248.023255813954, 'News'), (21028.410714285714, 'Productivity'), (18684.456790123455, 'Utilities'), (16485.764705882353, 'Lifestyle'), (14029.830708661417, 'Entertainment'), (7491.117647058823, 'Business'), (7003.983050847458, 'Education'), (4004.0, 'Catalogs'), (612.0, 'Medical')]


Here we can see Navigation apps are the most popular, followed by Reference and social networking apps. Lets quickly check the top apps in each of these categories. 

In [59]:
for app in free_english_ios_apps:
    if app[11]=='Navigation':
        print(app[1], ":", app[5])

Waze - GPS Navigation, Maps & Real-time Traffic : 345046
Google Maps - Navigation & Transit : 154911
Geocaching® : 12811
CoPilot GPS – Car Navigation & Offline Maps : 3582
ImmobilienScout24: Real Estate Search in Germany : 187
Railway Route Search : 5


Here we can see the Waze and Google Maps have hijacked the ratings along with Geocatching app. Rest of the apps doesn't have much influence. Also competing with such giants won't be a good strategy for our app.

Now let us look at Reference apps, what are them and how they are doing. 

In [33]:
for app in free_english_ios_apps:
    if app[11]=='Reference':
        print(app[1], ":", app[5])

Bible : 985920
Dictionary.com Dictionary & Thesaurus : 200047
Dictionary.com Dictionary & Thesaurus for iPad : 54175
Google Translate : 26786
Muslim Pro: Ramadan 2017 Prayer Times, Azan, Quran : 18418
New Furniture Mods - Pocket Wiki & Game Tools for Minecraft PC Edition : 17588
Merriam-Webster Dictionary : 16849
Night Sky : 12122
City Maps for Minecraft PE - The Best Maps for Minecraft Pocket Edition (MCPE) : 8535
LUCKY BLOCK MOD ™ for Minecraft PC Edition - The Best Pocket Wiki & Mods Installer Tools : 4693
GUNS MODS for Minecraft PC Edition - Mods Tools : 1497
Guides for Pokémon GO - Pokemon GO News and Cheats : 826
WWDC : 762
Horror Maps for Minecraft PE - Download The Scariest Maps for Minecraft Pocket Edition (MCPE) Free : 718
VPN Express : 14
Real Bike Traffic Rider Virtual Reality Glasses : 8
教えて!goo : 0
Jishokun-Japanese English Dictionary & Translator : 0


In this category, Bible, Quran and dictionary apps have influenced the ratings quite a bit. There a few guides too available in this category. If we can create a guide for something that is in high demand, then only we can create a successful app. So venturing into this category might also be not a great idea to start off with. 

So let us go to the next category which is social networking. This category, without any analysis we can guess that is already very strong category because of the big names likes Facebook, instagram, twitter etc. But lets cross check our general knowledge with data. 

In [71]:
count=0
for app in free_english_ios_apps:
    if app[11]=='Social Networking':
        count+=1
        print(app[1], ":", app[5])
        if count==25:                     # to print only 25 apps from the long list
            break

Facebook : 2974676
Pinterest : 1061624
Skype for iPhone : 373519
Messenger : 351466
Tumblr : 334293
WhatsApp Messenger : 287589
Kik : 260965
ooVoo – Free Video Call, Text and Voice : 177501
TextNow - Unlimited Text + Calls : 164963
Viber Messenger – Text & Call : 164249
Followers - Social Analytics For Instagram : 112778
MeetMe - Chat and Meet New People : 97072
We Heart It - Fashion, wallpapers, quotes, tattoos : 90414
InsTrack for Instagram - Analytics Plus More : 85535
Tango - Free Video Call, Voice and Chat : 75412
LinkedIn : 71856
Match™ - #1 Dating App. : 60659
Skype for iPad : 60163
POF - Best Dating App for Conversations : 52642
Timehop : 49510
Find My Family, Friends & iPhone - Life360 Locator : 43877
Whisper - Share, Express, Meet : 39819
Hangouts : 36404
LINE PLAY - Your Avatar World : 34677
WeChat : 34584


The guess was almost right. Facebook leads the way and there is a tight competition to face for any new app that comes into this category. Looking at this past data and seeing Telegram with 7573 should also give a good indication that if we can create a feature rich innovative social networking app, there are still chances. But we might not venture into this category at the moment due to high competition. 

It was surprising not to find instagram and twitter in the list. So lets just quickly check for them before we go into the next category. 

In [35]:
for app in free_english_ios_apps:
    if app[1]=='Instagram':
        print(app[1], ":", app[5], app[11])
    if app[1]=='Twitter':
        print(app[1], ":", app[5], app[11])

Instagram : 2161558 Photo & Video
Twitter : 354058 News


Instagram is listed under Photo and video while Twitter under News. They are not among the social network. But most people consider them the 'Social media', and hence our conclusion of high competition is justified again. 

In [60]:
for app in free_english_ios_apps:
    if app[11]=='Music':
        print(app[1], ":", app[5])

Pandora - Music & Radio : 1126879
Spotify Music : 878563
Shazam - Discover music, artists, videos & lyrics : 402925
iHeartRadio – Free Music & Radio Stations : 293228
SoundCloud - Music & Audio : 135744
Magic Piano by Smule : 131695
Smule Sing! : 119316
TuneIn Radio - MLB NBA Audiobooks Podcasts Music : 110420
Amazon Music : 106235
SoundHound Song Search & Music Player : 82602
Sonos Controller : 48905
Bandsintown Concerts : 30845
Karaoke - Sing Karaoke, Unlimited Songs! : 28606
My Mixtapez Music : 26286
Sing Karaoke Songs Unlimited with StarMaker : 26227
Ringtones for iPhone & Ringtone Maker : 25403
Musi - Unlimited Music For YouTube : 25193
AutoRap by Smule : 18202
Spinrilla - Mixtapes For Free : 15053
Napster - Top Music & Radio : 14268
edjing Mix:DJ turntable to remix and scratch music : 13580
Free Music - MP3 Streamer & Playlist Manager Pro : 13443
Free Piano app by Yokee : 13016
Google Play Music : 10118
Certified Mixtapes - Hip Hop Albums & Mixtapes : 9975
TIDAL : 7398
YouTube Mu

* Music apps are also already a saturated category like social networking. 
* At the same time weather apps wouldn't be very profitable as it is a very specialised category that also needs very accurate live data on a daily basis. So weather app won't be a very profitable app 
* Next one to check is Books

In [61]:
for app in free_english_ios_apps:
    if app[11]=='Book':
        print(app[1], ":", app[5])

Kindle – Read eBooks, Magazines & Textbooks : 252076
Audible – audio books, original series & podcasts : 105274
Color Therapy Adult Coloring Book for Adults : 84062
OverDrive – Library eBooks and Audiobooks : 65450
HOOKED - Chat Stories : 47829
BookShout: Read eBooks & Track Your Reading Goals : 879
Dr. Seuss Treasury — 50 best kids books : 451
Green Riding Hood : 392
Weirdwood Manor : 197
MangaZERO - comic reader : 9
ikouhoushi : 0
MangaTiara - love comic reader : 0
謎解き : 0
謎解き2016 : 0


* In the book category kindle and audible are leading. But other than that there are very less competition. So that gives us some hope. If we can bring a popular book into an app, or combine one of the popular category with book, we might have a winning combination. We will take a decision on this category after going through the google app data also. 

* Next category to analys is Food and drinks.

In [38]:
for app in free_english_ios_apps:
    if app[11]=='Food & Drink':
        print(app[1], ":", app[5])

Starbucks : 303856
Domino's Pizza USA : 258624
OpenTable - Restaurant Reservations : 113936
Allrecipes Dinner Spinner : 109349
DoorDash - Food Delivery : 25947
UberEATS: Uber for Food Delivery : 17865
Postmates - Food Delivery, Faster : 9519
Dunkin' Donuts - Get Offers, Coupons & Rewards : 9068
Chick-fil-A : 5665
McDonald's : 4050
Deliveroo: Restaurant Delivery - Order Food Nearby : 1702
SONIC Drive-In : 1645
Nowait Guest : 1625
7-Eleven, Inc. : 1356
Outback : 805
Bon Appetit : 750
Starbucks Keyboard : 457
Whataburger : 197
Delish Eatmoji Keyboard : 154
Lieferheld - Delicious food delivery service : 29
Lieferando.de : 29
McDo France : 22
Chefkoch - Rezepte, Kochen, Backen & Kochbuch : 20
Youmiam : 9
Marmiton Twist : 2
Open Food Facts : 1


* Most of the big players are either in food business or food delivery business. Since we are not planning to create any physical products or delivery service, this category might not be the best option to start with. 

* Finance category needs specialised knowledge and we might need to spend money to find the right people for the operations. Travel category is already very popular and offers big competition. Same goes with shopping too. 

After analysing the first 10 or so categories, the **one category that might make some sense is 'Book' category.** If we can find a popular book and offer some extra services and convert it into an app, it will be a good starting point to test our idea and to create a new app. So with that conclusion, we can start looking into Google apps data. 


# Finding Popular app on Google Play Store

For the google apps, the data regarding number of installs are already given. But they are not precise. It only indicates that the value is more than a certain number, for example 1000+, 50000+ etc

To get a general idea for our analysis, we will consider 1000+ as 1000 and so on to do our analysis. In order to do that we need to clean the data and remove the extra symbols and need to convert it to float from string. 

So let's find the average number of installation of apps in each category. 

In [62]:
category_list=[]                                # an empty list to add the list of categories
android_category=freq_table(free_english_google_apps,1)  # creating freq table of google apps

for category in android_category:               # iterating through android category dictionary
    total_installs=0
    length_of_category=0    
    for app in free_english_google_apps:        # iterating through google app dataset        
        app_category=app[1]                    
        if category==app_category:              # if category in the dictionary is same as that of app_category
            no_of_installs = app[5]
            no_of_installs = no_of_installs.replace(',','')    # replacing the string symbols with blank space
            no_of_installs = no_of_installs.replace('+','')
            total_installs += float(no_of_installs)            # converting the cleaned string into a float
            length_of_category += 1                            # counting the length of category
    avg_installs = total_installs/length_of_category
    storing_list = [avg_installs, category]                    # dummy list to store [avg_install,category]
    category_list.append(storing_list)                         # appending storing list to category list
    
print(sorted(category_list, reverse=True))                     # print the sorted category list
                

[[38456119.167247385, 'COMMUNICATION'], [24727872.452830188, 'VIDEO_PLAYERS'], [23253652.127118643, 'SOCIAL'], [17840110.40229885, 'PHOTOGRAPHY'], [16787331.344927534, 'PRODUCTIVITY'], [15588015.603248259, 'GAME'], [13984077.710144928, 'TRAVEL_AND_LOCAL'], [11640705.88235294, 'ENTERTAINMENT'], [10801391.298666667, 'TOOLS'], [9549178.467741935, 'NEWS_AND_MAGAZINES'], [8767811.894736841, 'BOOKS_AND_REFERENCE'], [7036877.311557789, 'SHOPPING'], [5201482.6122448975, 'PERSONALIZATION'], [5074486.197183099, 'WEATHER'], [4188821.9853479853, 'HEALTH_AND_FITNESS'], [4056941.7741935486, 'MAPS_AND_NAVIGATION'], [3695641.8198090694, 'FAMILY'], [3638640.1428571427, 'SPORTS'], [1986335.0877192982, 'ART_AND_DESIGN'], [1924897.7363636363, 'FOOD_AND_DRINK'], [1833495.145631068, 'EDUCATION'], [1712290.1474201474, 'BUSINESS'], [1437816.2687861272, 'LIFESTYLE'], [1387692.475609756, 'FINANCE'], [1331540.5616438356, 'HOUSE_AND_HOME'], [854028.8303030303, 'DATING'], [817657.2727272727, 'COMICS'], [647317.817

Now we have a sorted list of the top categories along with their average installations. The top 10 categories are communication, video player, social, photography, productivity, game, travel and local, entertainment, tools and news and magazines. Now let us look deeper into these categories. 

In [63]:
i=0
for app in free_english_google_apps:
    if app[1]=='COMMUNICATION' and app[5]=='1,000,000,000+':   # to find top installed Communication apps
        i += 1
        print('No:',i, '',app[0], ':', app[5])

No: 1  WhatsApp Messenger : 1,000,000,000+
No: 2  Messenger – Text and Video Chat for Free : 1,000,000,000+
No: 3  Skype - free IM & video calls : 1,000,000,000+
No: 4  Google Chrome: Fast & Secure : 1,000,000,000+
No: 5  Gmail : 1,000,000,000+
No: 6  Hangouts : 1,000,000,000+


In [64]:
i=0
for app in free_english_google_apps:
    if app[1]=='COMMUNICATION' and app[5]=='500,000,000+':
        i += 1
        print('No:',i, '',app[0], ':', app[5])

No: 1  Google Duo - High Quality Video Calls : 500,000,000+
No: 2  imo free video calls and chat : 500,000,000+
No: 3  LINE: Free Calls & Messages : 500,000,000+
No: 4  UC Browser - Fast Download Private & Secure : 500,000,000+
No: 5  Viber Messenger : 500,000,000+


In [65]:
       
i=0
for app in free_english_google_apps:
    if app[1]=='COMMUNICATION' and app[5]=='100,000,000+':
        i += 1
        print('No:',i, '',app[0], ':', app[5])

No: 1  imo beta free calls and text : 100,000,000+
No: 2  Android Messages : 100,000,000+
No: 3  Who : 100,000,000+
No: 4  GO SMS Pro - Messenger, Free Themes, Emoji : 100,000,000+
No: 5  Firefox Browser fast & private : 100,000,000+
No: 6  Messenger Lite: Free Calls & Messages : 100,000,000+
No: 7  Kik : 100,000,000+
No: 8  KakaoTalk: Free Calls & Text : 100,000,000+
No: 9  Opera Mini - fast web browser : 100,000,000+
No: 10  Opera Browser: Fast and Secure : 100,000,000+
No: 11  Telegram : 100,000,000+
No: 12  Truecaller: Caller ID, SMS spam blocking & Dialer : 100,000,000+
No: 13  UC Browser Mini -Tiny Fast Private & Secure : 100,000,000+
No: 14  WeChat : 100,000,000+
No: 15  Yahoo Mail – Stay Organized : 100,000,000+
No: 16  BBM - Free Calls & Messages : 100,000,000+


* Communication : We can see that there are some major giants with a big share of the communication category. 

* Same will be true for Video players with youtube and social with facebook. Due to high competition, these categories aren't the best to enter. 

In [66]:
i=0
for app in free_english_google_apps:
    if app[1]=='PHOTOGRAPHY' and (app[5]=='1,000,000,000+' or app[5]=='100,000,000+'):
        i += 1
        print('No:',i, '',app[0], ':', app[5])

No: 1  B612 - Beauty & Filter Camera : 100,000,000+
No: 2  YouCam Makeup - Magic Selfie Makeovers : 100,000,000+
No: 3  Sweet Selfie - selfie camera, beauty cam, photo edit : 100,000,000+
No: 4  Google Photos : 1,000,000,000+
No: 5  Retrica : 100,000,000+
No: 6  Photo Editor Pro : 100,000,000+
No: 7  BeautyPlus - Easy Photo Editor & Selfie Camera : 100,000,000+
No: 8  PicsArt Photo Studio: Collage Maker & Pic Editor : 100,000,000+
No: 9  Photo Collage Editor : 100,000,000+
No: 10  Z Camera - Photo Editor, Beauty Selfie, Collage : 100,000,000+
No: 11  PhotoGrid: Video & Pic Collage Maker, Photo Editor : 100,000,000+
No: 12  Candy Camera - selfie, beauty camera, photo editor : 100,000,000+
No: 13  YouCam Perfect - Selfie Photo Editor : 100,000,000+
No: 14  Camera360: Selfie Photo Editor with Funny Sticker : 100,000,000+
No: 15  S Photo Editor - Collage Maker , Photo Collage : 100,000,000+
No: 16  AR effect : 100,000,000+
No: 17  Cymera Camera- Photo Editor, Filter,Collage,Layout : 100,00

* Picture editors, fancy camera apps etc are topping the Photography category. As there are quite a lot of tough competition already, it might not make sense to get into this category straight away to create a new app. 

Now let us look at Productivity category.


In [44]:
i=0
for app in free_english_google_apps:
    if app[1]=='PRODUCTIVITY'and (app[5]=='1,000,000,000+' or app[5]=='500,000,000+' or app[5]=='100,000,000+'):
        i += 1
        print('No:',i, '',app[0], ':', app[5])

No: 1  Microsoft Word : 500,000,000+
No: 2  Microsoft Outlook : 100,000,000+
No: 3  Microsoft OneDrive : 100,000,000+
No: 4  Microsoft OneNote : 100,000,000+
No: 5  Google Keep : 100,000,000+
No: 6  ES File Explorer File Manager : 100,000,000+
No: 7  Dropbox : 500,000,000+
No: 8  Google Docs : 100,000,000+
No: 9  Microsoft PowerPoint : 100,000,000+
No: 10  Samsung Notes : 100,000,000+
No: 11  SwiftKey Keyboard : 100,000,000+
No: 12  Google Drive : 1,000,000,000+
No: 13  Adobe Acrobat Reader : 100,000,000+
No: 14  Google Sheets : 100,000,000+
No: 15  Microsoft Excel : 100,000,000+
No: 16  WPS Office - Word, Docs, PDF, Note, Slide & Sheet : 100,000,000+
No: 17  Google Slides : 100,000,000+
No: 18  ColorNote Notepad Notes : 100,000,000+
No: 19  Evernote – Organizer, Planner for Notes & Memos : 100,000,000+
No: 20  Google Calendar : 500,000,000+
No: 21  Cloud Print : 500,000,000+
No: 22  CamScanner - Phone PDF Creator : 100,000,000+


* Productivity category is ruled by giants like microsoft and google. Entry for a new app won't be easy in this category. 
* From our earilier analysis we have found out the iOS game category is saturated. It looks like it will be true for google apps as well. 

So let us look at the next category 'Travel and Local'. 

In [45]:
i=0
for app in free_english_google_apps:
    if app[1]=='TRAVEL_AND_LOCAL':
        i += 1
        print('No:',i, '',app[0], ':', app[5])

No: 1  trivago: Hotels & Travel : 50,000,000+
No: 2  Hopper - Watch & Book Flights : 5,000,000+
No: 3  TripIt: Travel Organizer : 1,000,000+
No: 4  Trip by Skyscanner - City & Travel Guide : 500,000+
No: 5  CityMaps2Go Plan Trips Travel Guide Offline Maps : 1,000,000+
No: 6  KAYAK Flights, Hotels & Cars : 10,000,000+
No: 7  World Travel Guide by Triposo : 500,000+
No: 8  Booking.com Travel Deals : 100,000,000+
No: 9  Hostelworld: Hostels & Cheap Hotels Travel App : 1,000,000+
No: 10  Google Trips - Travel Planner : 5,000,000+
No: 11  GPS Map Free : 5,000,000+
No: 12  GasBuddy: Find Cheap Gas : 10,000,000+
No: 13  Southwest Airlines : 5,000,000+
No: 14  AT&T Navigator: Maps, Traffic : 10,000,000+
No: 15  VZ Navigator : 50,000,000+
No: 16  KakaoMap - Map / Navigation : 10,000,000+
No: 17  AirAsia : 10,000,000+
No: 18  Expedia Hotels, Flights & Car Rental Travel Deals : 10,000,000+
No: 19  Goibibo - Flight Hotel Bus Car IRCTC Booking App : 10,000,000+
No: 20  Allegiant : 1,000,000+
No: 21

* Travel and local category is quite popular  and diverse, but almsost all fields have already been covered and it looks like it is all managed by specialised service providers. As we are not planning to spend too much on offering a very specialised service, travel and local category might not be the best fit. 

Next category to look into is Entertainment. 



In [46]:
i=0
for app in free_english_google_apps:
    if app[1]=='ENTERTAINMENT' and (app[5]=='1,000,000,000+' or app[5]=='500,000,000+' or app[5]=='100,000,000+'):
        i += 1
        print('No:',i, '',app[0], ':', app[5])

No: 1  Hotstar : 100,000,000+
No: 2  Talking Angela : 100,000,000+
No: 3  IMDb Movies & TV : 100,000,000+
No: 4  Talking Ben the Dog : 100,000,000+
No: 5  Netflix : 100,000,000+


* Entertainment category needs specialised content that are fresh and entertaining. Since we don't want to get involved in that entertainment category will also not be the best fit. 

Now let us look at the category : tools.

In [47]:
i=0
for app in free_english_google_apps:
    if app[1]=='TOOLS' and (app[5]=='1,000,000,000+' or app[5]=='500,000,000+' or app[5]=='100,000,000+'):
        i += 1
        print('No:',i, '',app[0], ':', app[5])

No: 1  Google : 1,000,000,000+
No: 2  Google Translate : 500,000,000+
No: 3  Calculator : 100,000,000+
No: 4  Device Help : 100,000,000+
No: 5  Account Manager : 100,000,000+
No: 6  SHAREit - Transfer & Share : 500,000,000+
No: 7  Samsung Calculator : 100,000,000+
No: 8  Gboard - the Google Keyboard : 500,000,000+
No: 9  Google Korean Input : 100,000,000+
No: 10  Share Music & Transfer Files - Xender : 100,000,000+
No: 11  Tiny Flashlight + LED : 100,000,000+
No: 12  GO Keyboard - Cute Emojis, Themes and GIFs : 100,000,000+
No: 13  Speedtest by Ookla : 100,000,000+
No: 14  CM Locker - Security Lockscreen : 100,000,000+
No: 15  Applock : 100,000,000+
No: 16  Clean Master- Space Cleaner & Antivirus : 500,000,000+
No: 17  Lookout Security & Antivirus : 100,000,000+
No: 18  Google Now Launcher : 100,000,000+
No: 19  360 Security - Free Antivirus, Booster, Cleaner : 100,000,000+
No: 20  Samsung Smart Switch Mobile : 100,000,000+
No: 21  Avast Mobile Security 2018 - Antivirus & App Lock : 10

* Tools can be a great category to enter if we have a unique idea of a tool that most people are lacking at the moment. To find that we might need to run an expensive market research. Otherwise, it looks like the tools category offers many options already and it is saturated. So it won't be an easy entry for a new app. 

* Next category is News and Magazines. Since we don't have our own news agency and magazine, this category won't be the best genre to start. 

Now we are coming again to Books and references. 

In [48]:
i=0
for app in free_english_google_apps:
    if app[1]=='BOOKS_AND_REFERENCE' and (app[5]=='1,000,000,000+' or app[5]=='500,000,000+' or app[5]=='100,000,000+'):
        i += 1
        print('No:',i, '',app[0], ':', app[5])

No: 1  Google Play Books : 1,000,000,000+
No: 2  Bible : 100,000,000+
No: 3  Amazon Kindle : 100,000,000+
No: 4  Wattpad 📖 Free Books : 100,000,000+
No: 5  Audiobooks from Audible : 100,000,000+


Looks like there are not many giants in this category just like it was in iOS. So let us examine the whole data for this category. 

In [67]:
i=0
for app in free_english_google_apps:
    if app[1]=='BOOKS_AND_REFERENCE' :
        i += 1
        print('No:',i, '',app[0], ':', app[5])

No: 1  E-Book Read - Read Book for free : 50,000+
No: 2  Download free book with green book : 100,000+
No: 3  Wikipedia : 10,000,000+
No: 4  Cool Reader : 10,000,000+
No: 5  Free Panda Radio Music : 100,000+
No: 6  Book store : 1,000,000+
No: 7  FBReader: Favorite Book Reader : 10,000,000+
No: 8  English Grammar Complete Handbook : 500,000+
No: 9  Free Books - Spirit Fanfiction and Stories : 1,000,000+
No: 10  Google Play Books : 1,000,000,000+
No: 11  AlReader -any text book reader : 5,000,000+
No: 12  Offline English Dictionary : 100,000+
No: 13  Offline: English to Tagalog Dictionary : 500,000+
No: 14  FamilySearch Tree : 1,000,000+
No: 15  Cloud of Books : 1,000,000+
No: 16  Recipes of Prophetic Medicine for free : 500,000+
No: 17  ReadEra – free ebook reader : 1,000,000+
No: 18  Anonymous caller detection : 10,000+
No: 19  Ebook Reader : 5,000,000+
No: 20  Litnet - E-books : 100,000+
No: 21  Read books online : 5,000,000+
No: 22  English to Urdu Dictionary : 500,000+
No: 23  eBoox

After analysing the data, we can see that there are many reliogious and reference books here. There are some technical textbooks also available. Other than that not many interesting books are available to read. 

In [50]:
i=0
for app in free_english_google_apps:
    if 'Bible' in app[0] or 'Quran' in app[0] :
        i += 1
        print('No:',i, '',app[0], ':', app[5])

No: 1  Bible : 100,000,000+
No: 2  Al-Quran (Free) : 10,000,000+
No: 3  Al Quran (Tafsir & by Word) : 500,000+
No: 4  Al Quran Indonesia : 10,000,000+
No: 5  Al'Quran Bahasa Indonesia : 10,000,000+
No: 6  Al Quran Al karim : 1,000,000+
No: 7  Al Quran Audio (Full 30 Juz) : 1,000,000+
No: 8  Quran for All (Al-Huda Int.) : 100,000+
No: 9  Ayat - Al Quran : 5,000,000+
No: 10  Quran Juz-30 - Mahad al Zahra : 100,000+
No: 11  Al Quran : EAlim - Translations & MP3 Offline : 5,000,000+
No: 12  Al-Quran Al-Muallim : 10,000+
No: 13  Al-Quran 30 Juz free copies : 500,000+
No: 14  Al Quran MP3 - Quran Reading® : 1,000,000+
No: 15  Hafizi Quran 15 lines per page : 1,000,000+
No: 16  Al-Quran Ahmad Saud Offline : 100,000+
No: 17  Quran for Android : 10,000,000+
No: 18  Taha Al Junaid Quran Mp3 : 50,000+
No: 19  Muslim Pro - Prayer Times, Azan, Quran & Qibla : 10,000,000+
No: 20  Holy Quran Mehmet Emin Ay : 10,000+
No: 21  Quran Khmer Offline AY : 1,000+
No: 22  Elif Ba - Learn The Holy Quran : 50,0

Our analysis shows that there are many apps based on Bible and Quran. So similarly, it will be a good idea to create an app based on a popular book with interesting addon features. 

If we can transform a popular book into an app with interesting features, there is a chance that we can make some profits as books category offers lesser competition and with good research we can create a good demand too. 

Also, we can look into the possibility of combining the travel category and book category and create interesting travel books since in both categories such a possibility is missing. 


# Conclusion

The number of apps in iOS and Google play store are increasing day by day. There are more than 2 million iOS apps available on the App Store, and 2.1 million Android apps on Google Play as per the data from 2018! We have analyses a very small sample data from iOS app store and Google play store to find a profitable app profile. Due to our requirement we have cleaned our data to create a data set containing free and English apps. 

After doing analysis in this specific dataset we have found out 
* many categories like social networking, photography and video have high competition
* Categories like games, family are oversaturated
* Categories like tools, productivity are overshadowed by giants
* Categories like Travel, food, music, weather etc needs specialised services to backup

Out of these categories, the one category stood out on both iOS and google app data set was the 'Books' category. This category has lesser big names stealing the show and lesser competition. Some of the popular books in the history of mankind are huge in this category, such as the Bible and the Quaran. Next in line are the dictionaries. 

It clearly shows that if we can find an interesting and popular book to convert into an app, a great demand can definitely be created. If we can provide some interesting features as add-on to elevate the experience of a book, it can be a great idea for an app. 

Also, if the book category can be combined with one of the other top popular categories such as travel, food etc, it can prove to be a winning combination as such combinations are clearly lacking in these categories. 
